config/routes.rb
Rails.application.routes.draw do
  root 'links#index'

  resources :links, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  get '/comments' => 'comments#index'
  get '/newest' => 'links#newest', as: :newest_links

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :links
    has_many :comments
    has_many :votes
    has_secure_password
  
    validates :username,
              presence: true,
              length: { minimum: 3 },
              uniqueness: { case_sensitive: false }
  
    validates :password, length: { minimum: 8 }
  
    def owns_link?(link)
      self == link.user
    end
  
    def owns_comment?(comment)
      self == comment.user
    end
  
    def upvote(link)
      votes.create(upvote: 1, link: link)
    end
  
    def upvoted?(link)
      votes.exists?(upvote: 1, link: link)
    end
  
    def downvote(link)
      votes.create(downvote: 1, link: link)
    end
  
    def downvoted?(link)
      votes.exists?(downvote: 1, link: link)
    end
  
    def remove_vote(link)
      votes.find_by(link: link).destroy
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    def login(user)
      session[:user_id] = user.id
    end
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logout
      session.delete(:user_id)
      @current_user = nil
    end
  
    def logged_in?
      current_user.nil? ? false : true
    end
  
    helper_method :current_user, :logged_in?
  
    def prevent_unauthorized_user_access
      redirect_to root_path, notice: 'Sorry, you cannot access that page', status: :found unless logged_in?
    end
  
    def prevent_logged_in_user_access
      redirect_to root_path, notice: 'Sorry, you cannot access that page', status: :found if logged_in?
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :prevent_logged_in_user_access, except: :destroy
  before_action :prevent_unauthorized_user_access, only: :destroy

  def new
  end

  def create
    user = User.find_by(username: login_params[:username])

    if user && user.authenticate(login_params[:password])
      login(user)
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:notice] = 'Invalid username / password combination'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out'
  end

  private

  def login_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :prevent_logged_in_user_access

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path, notice: 'Logged in'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JumpNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body class="container">
    <%= render "shared/navbar" %>

    <main>
      <% if flash[:notice] %>
        <p class="alert alert-info">
          <%= flash[:notice] %>
        </p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul class="errors alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <%= link_to "jump news", root_path, class: "logo" %>

    <div class="navlinks">
      <%= link_to "new", newest_links_path %>
      <%= link_to "comments", comments_path %>

      <% unless logged_in? %>
        <%= link_to "signup", new_user_path %>
        <%= link_to "login", new_session_path %>
      <% end %>

      <% if logged_in? %>
        <%= link_to "submit a link", new_link_path %>
        <%= link_to "logout", sessions_path, method: :delete %>
      <% end %>
    </div>
  </nav>
</header>
© 2020 GitHub, Inc.

app/views/users/new.html.erb
<section class="register-user">
  <header>
    <h1>
      Create a new Account
    </h1>

    <div class="row">
      <div class="col-sm-6">
        <%= form_for @user do |f| %>
        <%= render "shared/errors", object: @user %>
        <div class="form-group">
          <%= f.text_field :username, class: "form-control", required: true, minlength: 3, placeholder: "username" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control", required: true, minlength: 8, placeholder: "password" %>
        </div>

        <div class="form-group">
          <%= f.button "Register", class: "btn btn-success" %>
        </div>

        <% end %>
      </div>
    </div>
  </header>
</section>